<a href="https://colab.research.google.com/github/Ravkeerat02/comp3122_labs/blob/master/101344680_data_sci(lab04).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

In [2]:
numpy.__version__


'1.21.6'

In [6]:
import array 
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np 

In [9]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [11]:
np.array([1.2,4.5,2,5,3])

array([1.2, 4.5, 2. , 5. , 3. ])

In [12]:
np.array(['king kong',1,4,2,5,3])

array(['king kong', '1', '4', '2', '5', '3'], dtype='<U21')

In [14]:
np.array([range(i,i+3) for i in [10,12,14]])

array([[10, 11, 12],
       [12, 13, 14],
       [14, 15, 16]])

In [16]:
for i in [2,4,6]:
  print(np.array(range(i,i+3)))

[2 3 4]
[4 5 6]
[6 7 8]


In [17]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.zeros(10,dtype = float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [21]:
np.random.random((4,5))

array([[0.36809232, 0.12693105, 0.97762926, 0.84163849, 0.33253175],
       [0.75682831, 0.86361729, 0.47661605, 0.45162545, 0.14074538],
       [0.63814143, 0.38263119, 0.57247208, 0.81518442, 0.41709463],
       [0.87849675, 0.03702249, 0.15276653, 0.93570174, 0.44530431]])

In [22]:
np.random.normal((4,5))
# avg - 0 


array([5.4864999 , 5.02115012])

In [23]:
np.random.randint(0,10,(5,4))

array([[8, 9, 2, 9],
       [9, 0, 3, 0],
       [6, 4, 4, 7],
       [0, 3, 7, 6],
       [5, 5, 5, 0]])

In [24]:
#creating frame 
#assigning values into the frame
np.empty(5)

array([1.2, 4.5, 2. , 5. , 3. ])

In [26]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional a

In [28]:
x1


array([5, 0, 3, 3, 7, 9])

In [29]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [30]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [31]:
 print("x3 ndim: ", x3.ndim)
 #refers iteration * rows * columns
 print("x3 shape:", x3.shape) 
 print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [32]:
print("dtype:",x3.dtype)

dtype: int64


In [33]:
x1[-1]

9

In [34]:
x1[-4]

3

In [37]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [38]:
x[::2]

NameError: ignored

In [40]:
x1[5::-2]

array([9, 3, 0])

In [41]:
x2[:2,:3]

array([[3, 5, 2],
       [7, 6, 8]])

In [43]:
#rows followed by columns
x2[::-1,::]

array([[1, 6, 7, 7],
       [7, 6, 8, 8],
       [3, 5, 2, 4]])

In [44]:
print(x2[:,0])

[3 7 1]


In [45]:
print(x2[:,3])

[4 8 7]


In [46]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[3 5]
 [7 6]]


In [49]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [50]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [52]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
grid = np.arange(1,10)
print(grid)

[1 2 3 4 5 6 7 8 9]


In [54]:
x1[1,np.newaxis]

array([0])

In [55]:
x1[:,np.newaxis]

array([[5],
       [0],
       [3],
       [3],
       [7],
       [9]])

In [58]:
x = np.array([4,5,6])
y = np.array([6,5,4])
np.concatenate([x,y])

array([4, 5, 6, 6, 5, 4])

In [60]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [62]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))


[ 1  2  3  3  2  1 99 99 99]


In [63]:
np.concatenate([grid,grid],axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
np.vstack([x, grid])


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [68]:
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [69]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [70]:
grid = np.arange(16).reshape((4, 4))
grid


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)


[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
