<a href="https://colab.research.google.com/github/Ravkeerat02/comp3122_labs/blob/master/101344680_comp3122_ex05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [2]:
x = np.array([-2,-1,0,1,2])
x#absolute
abs(x) 

array([2, 1, 0, 1, 2])

In [4]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [6]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [7]:
x = ([3-4j,4-3j,2+0j,0+1j])
np.abs(x)

array([5., 5., 2., 1.])

In [8]:
theta = np.linspace(0,np.pi,3)

In [9]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))


theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
